  version: '3'
  services:
    app:
      container_name: ${APP_CONTAINER_NAME:-app_container}
      build: .
      image: my_app_image:latest
      ports:
        - "8080:8080"  # Replace with actual port numbers or ensure environment variables are set
        # - "9003:9003"
      restart: on-failure
      volumes:
        - ./data:/var/www/data
        - ./src:/var/www/application
      depends_on:
        - mariadb     
      networks:
        - fullstack
      extra_hosts:
        - "host.docker.internal:host-gateway"
      # environment:
      #    XDEBUG_MODE: develop,debug
      #    XDEBUG_CONFIG: client_host=host.docker.internal start_with_request=yes


    application-nginx:
      image: nginx:alpine
      container_name: ${NGINX_CONTAINER_NAME:-nginx_container}
      restart: always
      tty: true
      environment:
        - APPLICATION_UPSTREAM=${APPLICATION_UPSTREAM:-app:8080}
      volumes:
        - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
        - ./docker/nginx/templates/:/etc/nginx/templates/
        - ./src:/var/www/application/
      ports:
        - "8081:80"
        - "445:443"
      networks:
        - fullstack

    mariadb:
      image: mariadb:10.6
      container_name: ${MARIADB_CONTAINER_NAME:-mariadb_container}
      ports:
        - "3306:3306"
      environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root_password}
        MYSQL_DATABASE: example
        MYSQL_USER: ${DB_USER:-db_user}
        MYSQL_PASSWORD: ${DB_PASSWORD:-db_password}

    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      depends_on:
        - mariadb
      environment:
        - PMA_ARBITRARY=1
        - MYSQL_USER=${DB_USER:-db_user}
        - MYSQL_PASSWORD=${DB_PASSWORD:-db_password}
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-root_password}
        - UPLOAD_LIMIT=64M
      networks:
        - fullstack

  volumes:
    api:
    database_mysql:                 
   
  networks:
    fullstack:
      driver: bridge

  